Repository GoogleCloudPlatform/pcap-sidecar, pull requests merged in 2025-04, with the labels that each got.

#41 improve DNS JSON translations
  pcap-cli/go.mod
  pcap-cli/internal/transformer/json_translator.go
  pcap-cli/internal/transformer/translator_worker.go
  scripts/init
Labels: enhancement

#50 fix(pcapfsn): spurious GCS gRPC client library errors.
  pcap-fsnotify/internal/gcs/client_library_exporter.go
  pcap-fsnotify/internal/gcs/exporter.go
  pcap-fsnotify/internal/gcs/fuse_exporter.go
  pcap-fsnotify/internal/log/logger.go
Labels: bug, go

#52 feat(init): skip file generating PCAP engines if GCS is disabled.
  scripts/init
  tcpdumpw/go.mod
  tcpdumpw/go.sum
  tcpdumpw/pkg/filter/dns_filter_provider.go
Labels: enhancement

#53 fix(init): if `PCAP_GCS_BUCKET` is not set or it is empty,
  scripts/init
Labels: enhancement

#55 docs: GCS is optional & disabled by default. Cloud Logging is enabled by default
  README.md
Labels: documentation

#54 feat(pcap-cli): PCAP verbosity to control size of JSON translations.
  pcap-cli/internal/pb/packet.pb.go
  pcap-cli/internal/transformer/json_translator.go
  pcap-cli/internal/transformer/proto_translator.go
  pcap-cli/internal/transformer/transformer.go
  pcap-cli/internal/transformer/utils.go
  pcap-cli/pkg/pcap/gopacket_engine.go
  pcap-cli/pkg/pcap/pcap.go
  pcap-cli/schema/proto/packet.proto
  scripts/init
  scripts/start_tcpdumpw
  tcpdumpw/main.go
Labels: enhancement, go

#56 fix(pcap-cli): make TCP JSON translation even less verbose.
  config/go.mod
  config/go.sum
  config/internal/config/config.go
  config/internal/config/envs.go
  config/internal/config/keys.go
  config/main.go
  config/pcap.jsonnet
  config/pkg/config/config.go
  config/pkg/config/utils.go
  pcap-cli/internal/transformer/json_translator.go
  pcap-fsnotify/internal/gcs/client_library_exporter.go
  pcap.conf
  scripts/init
Labels: enhancement, go

#59 feat(licensing): script to generate third party license list
  Dockerfile
  cloudbuild.yaml
  licensing/create_license_csv
  licensing/third_party_licenses/LICENSES.csv
Labels: enhancement

#60 feat(config): add support for CLI flags ( override env vars )
  config/go.mod
  config/go.sum
  config/internal/config/config.go
  config/internal/config/envs.go
  config/internal/config/flags.go
  config/internal/config/keys.go
  config/main.go
  config/pcap.jsonnet
Labels: enhancement, go

#61 fix(pcapfsn): writer double closure: 1. at export, 2. at callback.
  pcap-fsnotify/internal/gcs/client_library_exporter.go
  pcap-fsnotify/internal/gcs/exporter.go
  pcap-fsnotify/internal/gcs/fuse_exporter.go
Labels: bug, go
